### ISSUE TITLE
[Feature] Respect .ffizer.yml in Addition to .ffizer.yaml

### ISSUE THREAD

**Issue by zicklag** [ffizer/ffizer#162]
I noticed that ffizer will not respect an ffizer yaml file that ends in `.yml` instead of `.yaml`. This could confuse some users if they didn't notice it.

**Comment by davidB** [comment]
If ffizer support both extension, what is your suggestion if both file exist ?

**Comment by zicklag** [comment]
That is a good question. I see two options:

- ffizer will pick one of them ( probably the `.yaml` because that is the one it has been using ) and then print a warning that it detected two files and that it will use the one that it picked.
- ffizer will exit without doing anything and ask you to delete or move the one that you do not want to use.
