### ISSUE TITLE
ffizer silently fail if one of the ffizer.hbs files contains not escaped {{

### ISSUE THREAD

**Issue by iilyak** [ffizer/ffizer#195]
In cases when one of the ffizer.hbs contains non escaped `{{` the ffizer exits with non zero exit code without any meaningful error message. The only way to find the problematic file is to search for a file with 0 bytes in it.

I created a small reproducer https://gist.github.com/iilyak/f3352a2ae5ea632610bdd191f6f685e8
Here is the output
```
❯ rm -rf ttttttt/ && ffizer apply --source reproducer/ --destination ttttttt --update-mode Override


Configure variables

foo: myfoo


Plan to execute

   - make dir        ttttttt
   - add file         └─bar

~/dev
❯ echo $?
1

~/dev
❯ ls -la ttttttt/
total 8
drwxr-xr-x   2 iilyak users 4096 Jan 23 18:09 .
drwxr-xr-x 100 iilyak users 4096 Jan 23 18:09 ..
-rw-r--r--   1 iilyak users    0 Jan 23 18:09 bar
```

**Comment by davidB** [comment]
Thanks for reporting the issue with a reproducible case. I don't when the log stopped to work. I'm releasing 1.7.1 with the fix.

**Comment by iilyak** [comment]
Thank you for the fix.
