### ISSUE TITLE
Panic when applying a template

### ISSUE THREAD

**Issue by drivasperez** [ffizer/ffizer#54]
Hi,

I've been getting a panic in Ffizer 0.9.0, when applying a template, looks like a failing .unwrap(). Stack trace below: 

`name = 'ffizer'
operating_system = 'unix:Ubuntu'
crate_version = '0.9.0'
explanation = '''
Panic occurred in file 'src/libcore/result.rs' at line 1009
'''
method = 'Panic'
backtrace = '''
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized::h63e17ec3c9056468 (0x7f6e81596666)
   1: backtrace::capture::Backtrace::create::h9daf768f506c2ccb (0x7f6e8159574e)
   2: backtrace::capture::Backtrace::new::h86b73149f7417b9d (0x7f6e8159560d)
   3: human_panic::handle_dump::hdecd64e38b6fe626 (0x7f6e812aac00)
   4: ffizer::main::{{closure}}::h94eb8ae2ae6e936b (0x7f6e815c8617)
   5: std::panicking::rust_panic_with_hook::h8cbdfe43764887be (0x7f6e8159aec2)
             at src/libstd/panicking.rs:495
   6: std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1 (0x7f6e8159ac4d)
             at src/libstd/panicking.rs:398
   7: rust_begin_unwind (0x7f6e815b22c5)
             at src/libstd/panicking.rs:325
   8: core::panicking::panic_fmt::h4d67173bc68f6d5a (0x7f6e815b675b)
             at src/libcore/panicking.rs:95
   9: core::result::unwrap_failed::hd0c279d6e3f0bab1 (0x7f6e812bc0d1)
  10: ffizer::process::h52385e7807c213d4 (0x7f6e81301d9b)
  11: ffizer::main::hbc950faad6240cd0 (0x7f6e815c66a7)
  12: std::rt::lang_start::{{closure}}::hf601071dd1b5cfb3 (0x7f6e815ce252)
  13: main (0x7f6e815c3dac)
  14: __libc_start_main (0x7f6e80111b96)
  15: _start (0x7f6e81256869)
  16: <unknown> (0x0)'''
`

The template isn't too complex: it's three files which include two variables and some to_camel_case() calls. If you'd like, I can provide them as well.

Thanks!

**Comment by davidB** [comment]
Yes, provide the template and the command line you used.

Thanks for reporting the bugs.

**Comment by drivasperez** [comment]
Hi, I figured out what was going wrong this morning. I had forgotten to include variable definitions in a .ffizer.yaml file and it was choking on that.

**Comment by davidB** [comment]
do you mean a variable like `{{foo}}` inside a template xxx.ffizer.hbs without definition .ffizer.yaml ?

I'll try to find a way to provide a better feedback to user in this case.

**Comment by drivasperez** [comment]
Yes, that's right, I had forgotten to define `reducer_name` and `constant_name` for the template in the gist below:

[{{ to_camel_case(reducer_name) }}Actions.ts.ffizer.hbs](https://gist.github.com/drivasperez/87d0712f1d0fc7471cf8410adf50d730)

Thanks for your help!
