### ISSUE TITLE
Separate the template repository from template content

### ISSUE THREAD

**Issue by kskyten** [ffizer/ffizer#79]
If I understand correctly, the template contents are stored directly in the root of the template repository. Thus, if I want to refer to a template that is hosted on github, the template metadata is mixed in with the content. I think it would be cleaner to store the template contents inside a sub-directory like porteurbars does. Is it possible to define this behavior in the `.ffizer.yaml` file?

**Comment by davidB** [comment]
Yes meta data (.ffizer.yaml) is stored at the root of template.
No the root of the git repo should not be the root of template, I have some repo that host several templates.
No it's not possible (yet) to say the to ffizer that the root of template is in a subfolder. IMHO, this subfolder is 1 click or `cd` when user want to browse. TBH It's an open option to add, but I would like to not allow too much configuration and fragmentation in the format of template. So maybe later.

I also like the original idea that by default any git repo, regular project could be used as a template. in this case ffizer act like as `git clone` or `cp`. And then the user can tweak to add .ffizer.yaml to say ignore `.git` folder, and after convert some file into template `xxx.ffizer.hbs`, and tweak more....

**Comment by kskyten** [comment]
I like porteurbars' UI for this. By default `porteurbars repo target` will use `repo/template` as the content, but if you have multiple templates in a repo, you can use `porteurbars -b other repo target` to use `repo/other/template`. 

What do I do if I want a `README.md` file for the template repository and the template itself?

**Comment by davidB** [comment]
Currently If you want to have a README.md in the template and in the project:

```
+- README.md.ffizer.hbs (or README.md.ffizer.raw)
+- README.md
+- .ffizer.yaml
```

And into .ffizer.yaml

```yaml
ignores:
  - README.md
```

I agree in some case allowing to have the template separated could be simpler. So I'm OK to add the option, but I'm don't know when.

**Comment by davidB** [comment]
feature is part of version  1.2.0
