### ISSUE TITLE
Apply templates to a git branch

### ISSUE THREAD

**Issue by kskyten** [ffizer/ffizer#81]
This is easy to do manually, but it would be a nice convenience feature and would provide useful diffing/merging/overwriting with very little work.

**Comment by davidB** [comment]
It's planned to be the next (big) feature. It will allow ffizer to used to update an existing folder.

**Comment by davidB** [comment]
Sorry I maybe misunderstood, what is planned is not related to a git branch.

**Comment by davidB** [comment]
Can you details the usage (flow & goals) ? I'm not sure to understand what you requet.
